REFERENCE_DATA_CNT: 10 # LLM 답변시 참조 데이터 수
MODEL_NAME: meta-llama/Llama-3.1-8B-Instruct

postgresql:
  host: 192.168.2.102
  database: social
  user: postgres
  password: postgres
  port: 15432

neo4j:
  uri: neo4j://192.168.2.104:34102
  user: neo4j
  password: dnpdlqmdnpdj

openai:
  api_key: EMPTY
  base_url: http://192.168.2.106:8401/v1